workspace = { members = ["router-macro"] }
[package]
name = "new-router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linkme = "0.3.22"
router-macro = { path = "./router-macro" }
